{{- if not .Values.hostOs -}}{{- $_ := set .Values "hostOs" "ubuntu" -}}{{- end }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-vrouter-agent
  namespace: kube-system
  labels:
    app: contrail-cni
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: contrail-cni
        contrail_function: "contrail-vrouter-agent"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
{{- if eq .Values.hostOs "centos7" }}
      initContainers:
      - name: contrail-vrouter-compiler
        {{- if .Values.imageRepo }}
        image: "{{ .Values.imageRepo }}/{{ default "contrail-vrouter-compiler-centos7" .Values.compilerImageName }}:{{ .Values.contrailVersion }}"
        {{- else }}
        image: {{ default "contrail-vrouter-compiler-centos7" .Values.compilerImageName }}:{{ .Values.contrailVersion }}"
        {{- end  }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /usr/src/kernels
          name: usr-src-kernels
        env:
        - name: INSTALL_VROUTER_MODULE
          value: 'true'
{{- end }}
      containers:
      - name: contrail-agent
        {{- if .Values.imageRepo }}
        image: "{{ .Values.imageRepo }}/{{ default "contrail-agent" .Values.agentImageName }}-{{ .Values.containerOsRelease }}:{{ .Values.contrailVersion }}"
        {{- else }}
        image: "{{ default "contrail-agent" .Values.agentImageName }}"
        {{- end  }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: etc-contrailctl
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /usr/src
          name: usr-src
        - mountPath: /host/opt_cni_bin
          name: opt-cni-bin
        - mountPath: /host/etc_cni
          name: etc-cni
        - mountPath: /var/lib/contrail/
          name: contrail-varlib
        # This is a workaround just to make sure the directory is created on host
        - mountPath: /var/log/contrail/cni
          name: log-cni
      volumes:
      - name: etc-contrailctl
        configMap:
          name: contrailctl-config
          items:
          - key: agent-config
            path: agent.conf
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
{{- if eq .Values.hostOs "centos7" }}
      - name: usr-src-kernels
        hostPath:
          path: /usr/src/kernels
{{- end }}
      - name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: etc-cni
        hostPath:
          path: /etc/cni
      - name: contrail-varlib
        hostPath:
          path: /var/lib/contrail/
      - name: log-cni
        hostPath:
          path: /var/log/contrail/cni/
