{{ if .Values.contrailHA }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "analyticsdb.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "analyticsdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "analyticsdb.fullname" . }}
        contrail_function: "contrail-controller"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "contrail.role",
                        "operator": "In",
                        "values": ["controller"]
                      }
                    ]
                  }
                ]
              }
            }
          }
        scheduler.alpha.kubernetes.io/tolerations: >
          [
            {
              "key":"dedicated",
              "value":"master",
              "effect":"NoSchedule"
            },
           {
              "key":"CriticalAddonsOnly",
              "operator":"Exists"
           }
          ]
    spec:
      hostNetwork: true
      containers:
      - name: contrail-analyticsdb
        image: "{{ .Values.imageRepo }}/{{ default "contrail-analyticsdb" .Values.analyticsdbImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-analyticsdb
        - mountPath: /var/lib/cassandra
          name: analyticsdb-data
        - mountPath: /var/lib/zookeeper
          name: zookeeper-analyticsdb-data
      volumes:
      - name: contrailctl-analyticsdb
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: analyticsdb-config
            path: analyticsdb.conf
      - name: analyticsdb-data
        emptyDir: {}
      - name: zookeeper-analyticsdb-data
        emptyDir: {}
{{ end }}
