apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-analyticsdb
  namespace: kube-system
  labels:
    app: contrail-cni
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: contrail-cni
        contrail_function: contrail-analyticsdb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "opencontrail.org/control-plane"
                operator: In
                values:
                - true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-analyticsdb
        {{- if .Values.imageRepo }}
        image: "{{ .Values.imageRepo }}/{{ default "contrail-analyticsdb" .Values.analyticsdbImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        {{- else }}
        image: "{{ default "contrail-analyticsdb" .Values.analyticsdbImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        {{- end }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-analyticsdb
        - mountPath: /var/lib/cassandra
          name: analyticsdb-data
        - mountPath: /var/lib/zookeeper
          name: zookeeper-analyticsdb-data
      volumes:
      - name: contrailctl-analyticsdb
        configMap:
          name: contrailctl-config
          items:
          - key: analyticsdb-config
            path: analyticsdb.conf
      - name: analyticsdb-data
        emptyDir: {}
      - name: zookeeper-analyticsdb-data
        emptyDir: {}
