{{ if not .Values.contrailHA }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "controller.fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "controller.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "controller.fullname" . }}
        contrail_function: "contrail-controller"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "kubeadm.alpha.kubernetes.io/role",
                        "operator": "In",
                        "values": ["master"]
                      }
                    ]
                  }
                ]
              }
            }
          }
        scheduler.alpha.kubernetes.io/tolerations: >
          [
            {
              "key":"dedicated",
              "value":"master",
              "effect":"NoSchedule"
            },
           {
              "key":"CriticalAddonsOnly",
              "operator":"Exists"
           }
          ]
    spec:
      hostNetwork: true
      containers:
      - name: contrail-controller
        image: "{{ .Values.imageRepo }}/{{ default "contrail-controller" .Values.controllerImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-controller
        - mountPath: /var/lib/cassandra
          name: configdb-data
        - mountPath: /var/lib/zookeeper
          name: zookeeper-data
      - name: contrail-analyticsdb
        image: "{{ .Values.imageRepo }}/{{ default "contrail-analyticsdb" .Values.analyticsdbImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-analyticsdb
        - mountPath: /var/lib/cassandra
          name: analyticsdb-data
      - name: contrail-analytics
        image: "{{ .Values.imageRepo }}/{{ default "contrail-analytics" .Values.analyticsImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-analytics
      - name: contrail-kube-manager
        image: "{{ .Values.imageRepo }}/{{ default "contrail-kube-manager" .Values.kubeManagerImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-kube-manager
      volumes:
      - name: contrailctl-controller
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: controller-config
            path: controller.conf
      - name: contrailctl-analyticsdb
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: analyticsdb-config
            path: analyticsdb.conf
      - name: contrailctl-analytics
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: analytics-config
            path: analytics.conf
      - name: contrailctl-kube-manager
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key: kube-manager-config
            path: kubemanager.conf
      - name: configdb-data
        emptyDir: {}
      - name: analyticsdb-data
        emptyDir: {}
      - name: zookeeper-data
        emptyDir: {}
{{ end }}