apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-kube-manager
  namespace: kube-system
  labels:
    app: contrail-cni
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.contrailVersion }}"
spec:
  template:
    metadata:
      labels:
        app: contrail-cni 
        contrail_function: contrail-kube-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "opencontrail.org/control-plane"
                operator: In
                values:
                - true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: contrail-kube-manager
        {{- if .Values.imageRepo }}
        image: "{{ .Values.imageRepo }}/{{ default "contrail-kube-manager" .Values.kubeManagerImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        {{- else }}
        image: "{{ default "contrail-kube-manager" .Values.kubeManagerImageName }}-{{ .Values.osRelease }}:{{ .Values.contrailVersion }}"
        {{- end }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/contrailctl
          name: contrailctl-kube-manager
      volumes:
      - name: contrailctl-kube-manager
        configMap:
          name: contrailctl-config
          items:
          - key: kube-manager-config
            path: kubemanager.conf
